# Generated by Django 5.0 on 2024-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_rename_sub_category_name_subcategory_subcatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcatname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
