# Generated by Django 5.0 on 2024-01-31 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_subcategory_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=255, null=True)),
                ('profileImage', models.ImageField(default='images/profile_img.jpg', null=True, upload_to='CustomerProfileImages/')),
                ('bio', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('country', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('twitterp', models.CharField(max_length=255, null=True)),
                ('facebookp', models.CharField(max_length=255, null=True)),
                ('instap', models.CharField(max_length=255, null=True)),
                ('linkedinp', models.CharField(max_length=255, null=True)),
                ('datetimep', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
