# Generated by Django 5.0 on 2024-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_customerprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
