# Generated by Django 5.0.1 on 2024-02-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='facebookp',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='instap',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='linkedinp',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='twitterp',
        ),
    ]
