# Generated by Django 5.0.1 on 2024-02-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_paid',
            field=models.FloatField(null=True),
        ),
    ]
