# Generated by Django 5.0.1 on 2024-02-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_order_total_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount_paid',
        ),
    ]
