# Generated by Django 5.0.1 on 2024-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_remove_order_total_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alt_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
